language: rust
cache: cargo
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo test
  - cargo clippy --all -- -D warnings
  - cargo fmt --all -- --check
