[workspace]

members = [
    "day01",
    "day02",
    "day03",
    "day04",
    "day06",
    "day08",
    "day09",
    "day10",
    "day11",
    "day12",
    "day16",
    "day18",
    "day20",
    "day22",
]
