[package]
name = "day25"
description = "Advent of Code - Day 25"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32"
regex = "~1.1.0"